export enum PlayerStatus {
  STOPPED = 0,
  DESTROYING = 1,
  DESTROYED = 2,
  LOADING = 3,
  LOADED = 4,
  PLAYING = 5,
  PLAYED = 6,
  PAUSED = 7,
  CHANGING = 9,
  SEEKING = 8,
}

export enum PlayerEventType {
  LOADING = "loading",
  LOADED = "loaded",
  PLAYING = "playing",
  PLAYED = "played",
  PAUSED = "paused",
  STOPPED = "stopped",
  ENDED = "ended",
  SEEKING = "seeking",
  SEEKED = "seeked",
  CHANGING = "changing",
  CHANGED = "changed",
  TIMEOUT = "timeout",
  ERROR = "error",
  TIME = "time",
  RESUME = "resume",
  FIRST_AUDIO_RENDERED = "firstAudioRendered",
  FIRST_VIDEO_RENDERED = "firstVideoRendered",
  STREAM_UPDATE = "streamUpdate",
  PROGRESS = "progress",
  VOLUME_CHANGE = "volumeChange",
  SUBTITLE_DELAY_CHANGE = "subtitleDelayChange",
  LOADING_COMPLETE = "LOADING_COMPLETE",
}
